version: "3.8"

services:
  loki:
    image: grafana/loki:2.2.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - /mnt/c/Users/bird0/log-monitoring/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    restart: always

  promtail:
    image: grafana/promtail:2.2.1
    container_name: promtail
    volumes:
      - /mnt/c/Users/bird0/log-monitoring/log:/var/log
      - /mnt/c/Users/bird0/log-monitoring/promtail:/etc/promtail
    command:
      - -config.file=/etc/promtail/promtail-config.yaml
    restart: always

  grafana:
    image: grafana/grafana-enterprise:7.5.17-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /mnt/c/Users/bird0/log-monitoring/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
